// MOSBOT Academy - Mission Data
const MOSBOT_MISSIONS = [
  // ── EXCEL MISSIONS (10) ──
  {id:'ex1',type:'excel',title:'Fórmulas Básicas',desc:'Suma, resta, multiplicación y división en Excel.',
   q:'¿Cuál es el símbolo para iniciar una fórmula en Excel?',opts:['#','$','=','@'],ans:2,
   exp:'El signo "=" es obligatorio para iniciar cualquier fórmula en Excel. Sin él, Excel interpreta el contenido como texto.'},
  {id:'ex2',type:'excel',title:'BUSCARV (VLOOKUP)',desc:'Búsqueda vertical en tablas de datos.',
   q:'¿Qué función permite buscar un valor en la primera columna de una tabla?',opts:['BUSCARH','BUSCARV','BUSCAR','ÍNDICE'],ans:1,
   exp:'BUSCARV busca un valor en la primera columna de una tabla y devuelve un valor de la misma fila en otra columna. BUSCARH es para búsqueda horizontal.'},
  {id:'ex3',type:'excel',title:'SUMAR.SI (SUMIF)',desc:'Suma condicional de rangos.',
   q:'¿Cuál es la sintaxis correcta de SUMAR.SI?',opts:['=SUMAR.SI(rango, criterio, suma_rango)','=SUMAR(SI(criterio))','=SUM.IF(range, value)','=SUMIF(range)'],ans:0,
   exp:'La sintaxis es =SUMAR.SI(rango, criterio, suma_rango). Suma los valores que cumplen con el criterio especificado.'},
  {id:'ex4',type:'excel',title:'Formato Condicional',desc:'Resaltar celdas según reglas.',
   q:'¿En qué pestaña se encuentra el Formato Condicional en Excel?',opts:['Inicio','Insertar','Datos','Fórmulas'],ans:0,
   exp:'El Formato Condicional está en la pestaña Inicio, en el grupo Estilos. Permite aplicar formato automáticamente según criterios.'},
  {id:'ex5',type:'excel',title:'Tablas Dinámicas',desc:'Análisis y resumen de grandes volúmenes de datos.',
   q:'¿Cómo crear una tabla dinámica en Excel?',opts:['Insertar > Tabla dinámica','Datos > Tabla dinámica','Análisis > Tabla dinámica','Vista > Tabla dinámica'],ans:0,
   exp:'Las tablas dinámicas se crean desde Insertar > Tabla dinámica. Permiten resumir y analizar grandes volúmenes de datos rápidamente.'},
  {id:'ex6',type:'excel',title:'Gráficos en Excel',desc:'Visualización de datos con gráficos.',
   q:'¿Cuál es el primer paso para crear un gráfico?',opts:['Seleccionar datos','Elegir tipo de gráfico','Insertar > Gráfico','Formato > Estilos'],ans:0,
   exp:'Siempre debes seleccionar los datos primero antes de crear un gráfico. Los datos incluyen etiquetas y valores a visualizar.'},
  {id:'ex7',type:'excel',title:'Función SI (IF)',desc:'Evalúa condiciones lógicas.',
   q:'¿Cuál es la estructura correcta de la función SI?',opts:['=SI(condición; si_verdadero; si_falso)','=IF(condition, true, false)','=IF(true, false, condition)','=SI(true, false)'],ans:0,
   exp:'La estructura es =SI(condición; si_verdadero; si_falso). Evalúa si la condición es verdadera o falsa y devuelve el resultado correspondiente.'},
  {id:'ex8',type:'excel',title:'CONTAR.SI (COUNTIF)',desc:'Cuenta celdas que cumplen un criterio.',
   q:'¿Qué hace la función CONTAR.SI?',opts:['Suma valores','Cuenta celdas que cumplen un criterio','Promedia valores','Busca un valor'],ans:1,
   exp:'CONTAR.SI cuenta el número de celdas que cumplen con un criterio específico. Es diferente de SUMAR.SI que suma valores.'},
  {id:'ex9',type:'excel',title:'Validación de Datos',desc:'Restringir entradas en celdas.',
   q:'¿Dónde está la opción Validación de Datos en Excel?',opts:['Datos > Validación','Inicio > Validación','Insertar > Validación','Fórmulas > Validación'],ans:0,
   exp:'Validación de Datos está en la pestaña Datos. Permite restringir el tipo de datos que se pueden ingresar en una celda.'},
  {id:'ex10',type:'excel',title:'Proteger Hojas',desc:'Seguridad y protección de hojas de cálculo.',
   q:'¿Cuál es el beneficio principal de proteger una hoja de Excel?',opts:['Aumentar velocidad','Evitar cambios no autorizados','Comprimir el archivo','Crear copias de seguridad'],ans:1,
   exp:'Proteger una hoja impide que otros usuarios realicen cambios no autorizados. Puedes restringir ediciones, inserción de filas, etc.'},
  // ── WORD MISSIONS (10) ──
  {id:'wd1',type:'word',title:'Formato de Texto',desc:'Negrita, cursiva, subrayado y estilos.',
    q:'¿Cuál es el atajo de teclado para hacer texto en negrita en Word?',opts:['Ctrl+I','Ctrl+N','Ctrl+B','Ctrl+U'],ans:2,
    exp:'Ctrl+B es el atajo para negrita. Ctrl+I es para cursiva y Ctrl+U para subrayado. Estos atajos funcionan en Word y Excel.'},
  {id:'wd2',type:'word',title:'Estilos y Temas',desc:'Aplicar estilos predefinidos a documentos.',
    q:'¿Dónde se encuentran los Estilos predefinidos en Word?',opts:['Pestaña Insertar','Pestaña Diseño','Pestaña Inicio','Pestaña Referencias'],ans:2,
    exp:'Los Estilos están en la pestaña Inicio, en el grupo Estilos. Permite aplicar formatos predefinidos consistentes al documento.'},
  {id:'wd3',type:'word',title:'Tablas en Word',desc:'Crear y formatear tablas profesionales.',
    q:'¿Cómo insertas una tabla en Word?',opts:['Insertar > Tabla','Inicio > Tabla','Diseño > Tabla','Referencias > Tabla'],ans:0,
    exp:'Las tablas se insertan desde Insertar > Tabla. Puedes elegir el número de filas y columnas que necesites.'},
  {id:'wd4',type:'word',title:'Encabezados y Pies',desc:'Configurar encabezados y pies de página.',
    q:'¿En qué pestaña se configura el Encabezado y Pie de página?',opts:['Inicio > Encabezado','Insertar > Encabezado','Diseño > Encabezado','Vista > Encabezado'],ans:1,
    exp:'Los Encabezados y Pies de página se configuran desde la pestaña Insertar. Aparecen automáticamente en todas las páginas.'},
  {id:'wd5',type:'word',title:'Saltos de Página',desc:'Controlar la paginación del documento.',
    q:'¿Cuál es el atajo de teclado para insertar un salto de página?',opts:['Ctrl+Enter','Ctrl+Shift+Enter','Alt+Enter','Ctrl+P'],ans:0,
    exp:'Ctrl+Enter inserta un salto de página forzando el inicio de una nueva página. Útil para controlar la paginación.'},
  {id:'wd6',type:'word',title:'Listas y Viñetas',desc:'Organizar información con listas.',
    q:'¿En qué pestaña se encuentran las opciones de Listas y Viñetas?',opts:['Inicio > Párrafo > Viñetas','Insertar > Lista','Diseño > Lista','Referencias > Lista'],ans:0,
    exp:'Las Listas y Viñetas están en la pestaña Inicio, en el grupo Párrafo. Permiten organizar información de forma clara.'},
  {id:'wd7',type:'word',title:'Imágenes e Ilustraciones',desc:'Insertar y formatear elementos gráficos.',
    q:'¿Cómo insertas una imagen en un documento de Word?',opts:['Insertar > Imágenes','Inicio > Imágenes','Diseño > Imágenes','Vista > Imágenes'],ans:0,
    exp:'Las imágenes se insertan desde Insertar > Imágenes. Puedes seleccionar desde tu computadora o descargar de Internet.'},
  {id:'wd8',type:'word',title:'Comentarios y Revisión',desc:'Colaborar con comentarios en documentos.',
    q:'¿En qué pestaña se encuentran los Comentarios en Word?',opts:['Revisar > Nuevo comentario','Insertar > Comentario','Inicio > Comentario','Vista > Comentario'],ans:0,
    exp:'Los Comentarios están en la pestaña Revisar. Útiles para colaboración y feedback en documentos compartidos.'},
  {id:'wd9',type:'word',title:'Tabla de Contenido',desc:'Generar tabla de contenido automática.',
    q:'¿Cómo generas una Tabla de Contenido automática?',opts:['Referencias > Tabla de contenido','Insertar > Tabla de contenido','Inicio > Índice','Diseño > Contenido'],ans:0,
    exp:'La Tabla de Contenido se genera desde Referencias > Tabla de contenido. Se actualiza automáticamente con los títulos del documento.'},
  {id:'wd10',type:'word',title:'Combinar Correspondencia',desc:'Crear documentos personalizados en masa.',
    q:'¿En qué pestaña se encuentra la opción Combinar Correspondencia?',opts:['Correspondencia','Insertar','Inicio','Revisar'],ans:0,
    exp:'Combinar Correspondencia está en la pestaña Correspondencia. Permite generar múltiples documentos personalizados automáticamente.'}
];

const MOSBOT_RANKS = [
  {name:'Practicante MOS',minXP:0,icon:'🌱'},
  {name:'Aprendiz Office',minXP:300,icon:'📘'},
  {name:'Técnico Digital',minXP:600,icon:'💻'},
  {name:'Especialista MOS',minXP:1000,icon:'⭐'},
  {name:'Experto Office',minXP:1400,icon:'🏆'},
  {name:'Office Master',minXP:2000,icon:'👑'}
];

const MOSBOT_BADGES = [
  {id:'b1',name:'Primera Misión',desc:'Completa tu primera misión',icon:'🎯',req:1},
  {id:'b2',name:'Racha de 5',desc:'Completa 5 misiones',icon:'🔥',req:5},
  {id:'b3',name:'Excel Warrior',desc:'Completa todas las misiones Excel',icon:'📊',req:'allExcel'},
  {id:'b4',name:'Word Master',desc:'Completa todas las misiones Word',icon:'📝',req:'allWord'},
  {id:'b5',name:'Medio Camino',desc:'Completa 10 misiones',icon:'⚡',req:10},
  {id:'b6',name:'Casi Perfecto',desc:'Completa 15 misiones',icon:'💎',req:15},
  {id:'b7',name:'Graduado MOS',desc:'Completa las 20 misiones',icon:'🎓',req:20},
  {id:'b8',name:'Velocista',desc:'Completa 3 misiones seguidas correctas',icon:'⚡',req:'streak3'}
];
