// MOSBOT Academy - Mission Data
const MOSBOT_DATA_VERSION = 'word-tables-2026-01';
const MOSBOT_MISSIONS = [
  // ── EXCEL MISSIONS (10) ──
  {id:'ex1',type:'excel',title:'Fórmulas Básicas',desc:'Suma, resta, multiplicación y división en Excel.',
   q:'¿Cuál es el símbolo para iniciar una fórmula en Excel?',opts:['#','$','=','@'],ans:2,
   exp:'El signo "=" es obligatorio para iniciar cualquier fórmula en Excel. Sin él, Excel interpreta el contenido como texto.'},
  {id:'ex2',type:'excel',title:'BUSCARV (VLOOKUP)',desc:'Búsqueda vertical en tablas de datos.',
   q:'¿Qué función permite buscar un valor en la primera columna de una tabla?',opts:['BUSCARH','BUSCARV','BUSCAR','ÍNDICE'],ans:1,
   exp:'BUSCARV busca un valor en la primera columna de una tabla y devuelve un valor de la misma fila en otra columna. BUSCARH es para búsqueda horizontal.'},
  {id:'ex3',type:'excel',title:'SUMAR.SI (SUMIF)',desc:'Suma condicional de rangos.',
   q:'¿Cuál es la sintaxis correcta de SUMAR.SI?',opts:['=SUMAR.SI(rango, criterio, suma_rango)','=SUMAR(SI(criterio))','=SUM.IF(range, value)','=SUMIF(range)'],ans:0,
   exp:'La sintaxis es =SUMAR.SI(rango, criterio, suma_rango). Suma los valores que cumplen con el criterio especificado.'},
  {id:'ex4',type:'excel',title:'Formato Condicional',desc:'Resaltar celdas según reglas.',
   q:'¿En qué pestaña se encuentra el Formato Condicional en Excel?',opts:['Inicio','Insertar','Datos','Fórmulas'],ans:0,
   exp:'El Formato Condicional está en la pestaña Inicio, en el grupo Estilos. Permite aplicar formato automáticamente según criterios.'},
  {id:'ex5',type:'excel',title:'Tablas Dinámicas',desc:'Análisis y resumen de grandes volúmenes de datos.',
   q:'¿Cómo crear una tabla dinámica en Excel?',opts:['Insertar > Tabla dinámica','Datos > Tabla dinámica','Análisis > Tabla dinámica','Vista > Tabla dinámica'],ans:0,
   exp:'Las tablas dinámicas se crean desde Insertar > Tabla dinámica. Permiten resumir y analizar grandes volúmenes de datos rápidamente.'},
  {id:'ex6',type:'excel',title:'Gráficos en Excel',desc:'Visualización de datos con gráficos.',
   q:'¿Cuál es el primer paso para crear un gráfico?',opts:['Seleccionar datos','Elegir tipo de gráfico','Insertar > Gráfico','Formato > Estilos'],ans:0,
   exp:'Siempre debes seleccionar los datos primero antes de crear un gráfico. Los datos incluyen etiquetas y valores a visualizar.'},
  {id:'ex7',type:'excel',title:'Función SI (IF)',desc:'Evalúa condiciones lógicas.',
   q:'¿Cuál es la estructura correcta de la función SI?',opts:['=SI(condición; si_verdadero; si_falso)','=IF(condition, true, false)','=IF(true, false, condition)','=SI(true, false)'],ans:0,
   exp:'La estructura es =SI(condición; si_verdadero; si_falso). Evalúa si la condición es verdadera o falsa y devuelve el resultado correspondiente.'},
  {id:'ex8',type:'excel',title:'CONTAR.SI (COUNTIF)',desc:'Cuenta celdas que cumplen un criterio.',
   q:'¿Qué hace la función CONTAR.SI?',opts:['Suma valores','Cuenta celdas que cumplen un criterio','Promedia valores','Busca un valor'],ans:1,
   exp:'CONTAR.SI cuenta el número de celdas que cumplen con un criterio específico. Es diferente de SUMAR.SI que suma valores.'},
  {id:'ex9',type:'excel',title:'Validación de Datos',desc:'Restringir entradas en celdas.',
   q:'¿Dónde está la opción Validación de Datos en Excel?',opts:['Datos > Validación','Inicio > Validación','Insertar > Validación','Fórmulas > Validación'],ans:0,
   exp:'Validación de Datos está en la pestaña Datos. Permite restringir el tipo de datos que se pueden ingresar en una celda.'},
  {id:'ex10',type:'excel',title:'Proteger Hojas',desc:'Seguridad y protección de hojas de cálculo.',
   q:'¿Cuál es el beneficio principal de proteger una hoja de Excel?',opts:['Aumentar velocidad','Evitar cambios no autorizados','Comprimir el archivo','Crear copias de seguridad'],ans:1,
   exp:'Proteger una hoja impide que otros usuarios realicen cambios no autorizados. Puedes restringir ediciones, inserción de filas, etc.'},
  // ── WORD MISSIONS (20): DISEÑO Y MANIPULACIÓN DE TABLAS ──
  {id:'wd1',type:'word',title:'Crear Tablas en Word',desc:'Insertar tablas con filas y columnas.',
    q:'¿Desde qué pestaña se inserta una tabla en Microsoft Word?',opts:['Insertar > Tabla','Diseño > Tabla','Referencias > Tabla','Vista > Tabla'],ans:0,
    exp:'La pestaña Insertar contiene el comando Tabla, desde donde puedes elegir el tamaño inicial de filas y columnas.',tip:'Antes de insertar, calcula cuántos encabezados y registros necesitas para evitar rehacer la estructura.'},
  {id:'wd2',type:'word',title:'Convertir Texto en Tabla',desc:'Transformar texto separado en una tabla.',
    q:'¿Qué opción permite convertir texto separado por tabulaciones o comas en una tabla?',opts:['Insertar > Tabla > Convertir texto en tabla','Diseño > Bordes','Inicio > Ordenar','Vista > Cuadrícula'],ans:0,
    exp:'Convertir texto en tabla usa separadores como tabulaciones, comas o marcas de párrafo para formar columnas y filas.',tip:'Si el resultado sale desordenado, revisa primero que todos los renglones tengan el mismo separador.'},
  {id:'wd3',type:'word',title:'Herramientas de Tabla',desc:'Ubicar las pestañas contextuales de tablas.',
    q:'¿Qué pestañas aparecen al seleccionar una tabla en Word?',opts:['Diseño de tabla y Presentación','Inicio y Archivo','Correspondencia y Revisar','Referencias y Vista'],ans:0,
    exp:'Al seleccionar una tabla aparecen pestañas contextuales para aplicar estilos, bordes, sombreado, distribución y alineación.',tip:'Haz clic dentro de la tabla para que Word muestre las herramientas específicas.'},
  {id:'wd4',type:'word',title:'Estilos de Tabla',desc:'Aplicar formatos prediseñados.',
    q:'¿Para qué sirven los Estilos de tabla en Word?',opts:['Aplicar un diseño completo de bordes, colores y encabezados','Insertar una imagen dentro de una celda','Cambiar el idioma del documento','Crear una tabla de contenido'],ans:0,
    exp:'Los estilos de tabla aplican una apariencia consistente en segundos, incluyendo colores, bordes y énfasis visual.',tip:'Usa estilos sobrios para documentos formales y evita colores que dificulten la lectura.'},
  {id:'wd5',type:'word',title:'Fila de Encabezado',desc:'Destacar los títulos de columnas.',
    q:'¿Qué opción resalta la primera fila como títulos de la tabla?',opts:['Fila de encabezado','Primera columna','Filas con bandas','Repetir filas'],ans:0,
    exp:'Fila de encabezado marca la primera fila para diferenciar los títulos del resto de datos.',tip:'Los encabezados claros ayudan a que la tabla se entienda aunque tenga muchos registros.'},
  {id:'wd6',type:'word',title:'Filas con Bandas',desc:'Mejorar la lectura de tablas largas.',
    q:'¿Qué opción alterna el color de las filas para facilitar la lectura?',opts:['Filas con bandas','Borrador de bordes','Autoajustar ventana','Dividir tabla'],ans:0,
    exp:'Filas con bandas aplica sombreado alternado, lo que permite seguir cada renglón con más facilidad.',tip:'Es especialmente útil en listas de calificaciones, inventarios o reportes con muchas filas.'},
  {id:'wd7',type:'word',title:'Agregar Filas',desc:'Insertar nuevos registros en una tabla.',
    q:'¿Cómo agregas una fila debajo de la celda seleccionada?',opts:['Presentación > Insertar debajo','Diseño > Sombreado','Inicio > Pegar especial','Referencias > Insertar nota'],ans:0,
    exp:'En la pestaña Presentación de Herramientas de tabla puedes insertar filas arriba o debajo de la posición actual.',tip:'También puedes presionar Tab en la última celda para crear una nueva fila al final.'},
  {id:'wd8',type:'word',title:'Agregar Columnas',desc:'Insertar nuevos campos en una tabla.',
    q:'¿Qué comando inserta una columna a la derecha de la celda actual?',opts:['Presentación > Insertar a la derecha','Diseño > Efectos','Vista > Nueva ventana','Inicio > Aumentar sangría'],ans:0,
    exp:'Insertar a la derecha agrega una columna nueva justo después de la columna seleccionada.',tip:'Agrega columnas antes de aplicar ajustes de ancho para conservar mejor la distribución.'},
  {id:'wd9',type:'word',title:'Eliminar Partes de Tabla',desc:'Quitar filas, columnas o tabla completa.',
    q:'¿Dónde se encuentra el comando para eliminar filas, columnas o toda la tabla?',opts:['Presentación > Eliminar','Diseño > Colores','Insertar > Símbolo','Revisar > Control de cambios'],ans:0,
    exp:'El menú Eliminar de Presentación permite quitar celdas, filas, columnas o la tabla completa.',tip:'Selecciona exactamente lo que quieres borrar para no eliminar más contenido del necesario.'},
  {id:'wd10',type:'word',title:'Combinar Celdas',desc:'Unir varias celdas en una sola.',
    q:'¿Qué hace el comando Combinar celdas?',opts:['Une varias celdas seleccionadas en una sola','Ordena los datos de mayor a menor','Cambia el color del texto','Repite el encabezado en cada página'],ans:0,
    exp:'Combinar celdas crea una celda más grande a partir de varias celdas seleccionadas, útil para títulos internos.',tip:'Úsalo para encabezados agrupados, pero no abuses porque puede complicar la edición.'},
  {id:'wd11',type:'word',title:'Dividir Celdas',desc:'Separar una celda en varias partes.',
    q:'¿Para qué sirve Dividir celdas en una tabla de Word?',opts:['Separar una celda en varias filas o columnas','Cambiar el margen de la página','Insertar una portada','Guardar como PDF'],ans:0,
    exp:'Dividir celdas permite convertir una celda seleccionada en varias celdas internas según filas o columnas indicadas.',tip:'Es útil cuando una sección necesita más detalle que las demás.'},
  {id:'wd12',type:'word',title:'Dividir Tabla',desc:'Separar una tabla en dos.',
    q:'¿Qué comando separa una tabla en dos tablas independientes?',opts:['Presentación > Dividir tabla','Diseño > Dividir documento','Insertar > Salto de página','Vista > Organizar todo'],ans:0,
    exp:'Dividir tabla crea una nueva tabla a partir de la fila seleccionada, dejando la parte superior separada.',tip:'Coloca el cursor en la fila donde quieres iniciar la segunda tabla.'},
  {id:'wd13',type:'word',title:'Autoajustar Tabla',desc:'Ajustar tamaño según contenido o ventana.',
    q:'¿Qué opción ajusta automáticamente el ancho de las columnas al contenido?',opts:['Autoajustar al contenido','Distribuir filas','Repetir encabezado','Ordenar ascendente'],ans:0,
    exp:'Autoajustar al contenido cambia el ancho de cada columna según el texto que contiene.',tip:'Si la tabla debe ocupar todo el ancho de la página, usa Autoajustar a la ventana.'},
  {id:'wd14',type:'word',title:'Distribuir Columnas',desc:'Igualar el ancho de varias columnas.',
    q:'¿Qué comando deja varias columnas con el mismo ancho?',opts:['Distribuir columnas','Combinar celdas','Convertir a texto','Ver líneas de cuadrícula'],ans:0,
    exp:'Distribuir columnas iguala el ancho de las columnas seleccionadas para que la tabla se vea ordenada.',tip:'Selecciona todas las columnas que deseas igualar antes de aplicar el comando.'},
  {id:'wd15',type:'word',title:'Alineación de Celda',desc:'Colocar contenido dentro de celdas.',
    q:'¿Qué grupo permite centrar vertical y horizontalmente el contenido de una celda?',opts:['Alineación','Bordes','Datos','Tamaño de celda'],ans:0,
    exp:'El grupo Alineación de Presentación controla la posición del texto dentro de cada celda.',tip:'Centrar títulos y alinear datos de forma consistente mejora la presentación profesional.'},
  {id:'wd16',type:'word',title:'Dirección del Texto',desc:'Girar texto dentro de una celda.',
    q:'¿Qué comando cambia la orientación del texto dentro de una celda?',opts:['Dirección del texto','Márgenes de página','Vista de lectura','Insertar título'],ans:0,
    exp:'Dirección del texto permite girar el contenido de una celda, útil para encabezados estrechos.',tip:'Úsalo solo cuando ahorre espacio sin sacrificar legibilidad.'},
  {id:'wd17',type:'word',title:'Bordes de Tabla',desc:'Controlar líneas internas y externas.',
    q:'¿Qué herramienta permite elegir qué líneas de la tabla se muestran?',opts:['Bordes','Temas','Sinónimos','Comentarios'],ans:0,
    exp:'Bordes permite activar o quitar líneas internas, externas, superiores, inferiores o laterales.',tip:'Para documentos formales, combina bordes externos fuertes con líneas internas suaves.'},
  {id:'wd18',type:'word',title:'Sombreado de Celdas',desc:'Aplicar color de fondo a celdas.',
    q:'¿Qué comando cambia el color de fondo de una celda o fila?',opts:['Sombreado','Color de fuente','Marca de agua','Resaltar cambios'],ans:0,
    exp:'Sombreado aplica color de fondo a celdas seleccionadas para destacar encabezados o secciones.',tip:'Usa buen contraste entre fondo y texto para que la tabla siga siendo legible.'},
  {id:'wd19',type:'word',title:'Ordenar Datos',desc:'Clasificar contenido dentro de tablas.',
    q:'¿Qué comando ordena datos alfabética o numéricamente dentro de una tabla?',opts:['Ordenar','Filtrar','Buscar','Comparar'],ans:0,
    exp:'Ordenar clasifica filas por una columna elegida, ya sea de forma ascendente o descendente.',tip:'Si tu tabla tiene encabezados, marca la opción correspondiente para no ordenar la primera fila como dato.'},
  {id:'wd20',type:'word',title:'Repetir Encabezado',desc:'Mostrar títulos en tablas que ocupan varias páginas.',
    q:'¿Qué opción repite la fila de títulos cuando una tabla continúa en otra página?',opts:['Repetir filas de título','Dividir celdas','Autoajustar al contenido','Ver líneas de cuadrícula'],ans:0,
    exp:'Repetir filas de título hace que el encabezado aparezca automáticamente al inicio de cada página donde continúa la tabla.',tip:'Actívalo en tablas largas para que el lector siempre sepa qué representa cada columna.'}
];

const MOSBOT_RANKS = [
  {name:'Practicante MOS',minXP:0,icon:'🌱'},
  {name:'Aprendiz Office',minXP:300,icon:'📘'},
  {name:'Técnico Digital',minXP:600,icon:'💻'},
  {name:'Especialista MOS',minXP:1000,icon:'⭐'},
  {name:'Experto Office',minXP:1400,icon:'🏆'},
  {name:'Office Master',minXP:2000,icon:'👑'}
];

const MOSBOT_BADGES = [
  {id:'b1',name:'Primera Misión',desc:'Completa tu primera misión',icon:'🎯',req:1},
  {id:'b2',name:'Racha de 5',desc:'Completa 5 misiones',icon:'🔥',req:5},
  {id:'b3',name:'Excel Warrior',desc:'Completa todas las misiones Excel',icon:'📊',req:'allExcel'},
  {id:'b4',name:'Word Master',desc:'Completa todas las misiones Word',icon:'📝',req:'allWord'},
  {id:'b5',name:'Medio Camino',desc:'Completa 10 misiones',icon:'⚡',req:10},
  {id:'b6',name:'Casi Perfecto',desc:'Completa 15 misiones',icon:'💎',req:15},
  {id:'b7',name:'Graduado MOS',desc:'Completa todas las misiones',icon:'🎓',req:'allMissions'},
  {id:'b8',name:'Velocista',desc:'Completa 3 misiones seguidas correctas',icon:'⚡',req:'streak3'}
];
